#!/usr/bin/env python3
"""
Generate summary from transcription and create markdown file
Usage: generate_summary.py <combined_text_file> <language> <output_dir> <original_url>
"""

import sys
import os
import re
import json
from datetime import datetime

def sanitize_filename(text):
    """Remove special characters from filename"""
    # Remove or replace special characters
    text = re.sub(r'[<>:"/\\|?*]', '', text)
    # Replace spaces and other chars with underscores
    text = re.sub(r'[^a-zA-Z0-9\u4e00-\u9fff_\-]', '_', text)
    # Remove multiple underscores
    text = re.sub(r'_+', '_', text)
    # Trim underscores from ends
    text = text.strip('_')
    # Limit length
    return text[:100] if len(text) > 100 else text

def generate_summary(text, language):
    """Generate a summary from the full transcription"""
    # For now, create a structured summary
    # In a real implementation, this could call an LLM
    
    paragraphs = [p.strip() for p in text.split('\n\n') if p.strip()]
    
    if language == 'zh':
        # Traditional Chinese summary structure
        summary = "## 摘要\n\n"
        summary += "以下是這段影片的重點整理：\n\n"
        
        # Extract key points (first few sentences from each paragraph)
        key_points = []
        for para in paragraphs[:5]:  # Limit to first 5 paragraphs
            sentences = para.split('。')
            if sentences:
                key_points.append(sentences[0] + '。')
        
        if key_points:
            summary += "### 重點\n"
            for point in key_points[:10]:  # Max 10 points
                if len(point.strip()) > 5:
                    summary += f"- {point.strip()}\n"
            summary += "\n"
        
        summary += "### 完整內容\n"
        
    else:
        # English summary structure
        summary = "## Summary\n\n"
        summary += "Key points from this video:\n\n"
        
        # Extract key points
        key_points = []
        for para in paragraphs[:5]:
            sentences = para.split('.')
            if sentences:
                key_points.append(sentences[0].strip() + '.')
        
        if key_points:
            summary += "### Key Points\n"
            for point in key_points[:10]:
                if len(point.strip()) > 5:
                    summary += f"- {point.strip()}\n"
            summary += "\n"
        
        summary += "### Full Transcription\n"
    
    return summary

def main():
    if len(sys.argv) < 4:
        print("Usage: generate_summary.py <combined_text_file> <language> <output_dir> <original_url>")
        sys.exit(1)
    
    text_file = sys.argv[1]
    language = sys.argv[2]
    output_dir = sys.argv[3]
    original_url = sys.argv[4] if len(sys.argv) > 4 else ""
    
    # Read combined transcription
    with open(text_file, 'r', encoding='utf-8') as f:
        full_text = f.read()
    
    if not full_text.strip():
        print("Error: Empty transcription")
        sys.exit(1)
    
    # Generate summary
    summary = generate_summary(full_text, language)
    
    # Create markdown content
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')
    
    # Get video title from text (first line or generate one)
    first_line = full_text.split('\n')[0][:50].strip()
    video_title = first_line if first_line else "YouTube_Video"
    
    # Create safe filename
    safe_title = sanitize_filename(video_title)
    if not safe_title:
        safe_title = "youtube_transcription"
    
    filename = f"{safe_title}.md"
    output_path = os.path.join(output_dir, filename)
    
    # Build markdown content
    md_content = f"# {video_title}\n\n"
    md_content += f"**Original Link:** {original_url}\n\n"
    md_content += f"**Transcribed:** {timestamp}\n\n"
    md_content += "---\n\n"
    md_content += summary
    md_content += "\n\n"
    md_content += full_text
    md_content += "\n\n---\n"
    md_content += f"*Generated by YouTube Transcriber Skill*\n"
    
    # Write markdown file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(md_content)
    
    print(f"Created: {output_path}")
    print(f"Filename: {filename}")

if __name__ == '__main__':
    main()
